version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nt@post
      POSTGRES_DB: nest
    networks:
      - nabin

networks:
  nabin:
